### ISSUE TITLE
Alert messages shouldn't be passed via GET params

### ISSUE THREAD

**Issue by jindrichmynarz** [opendatacz/pc-filing-app#1]
Alert messages shouldn't be passed via GET params, to prevent execution of any JavaScript, [see here](http://lod2.vse.cz:8080/pc-filing-app/register-buyer.jsp?t=error&m=%3Cscript%20type%3D%22text%2Fjavascript%22%3Ealert%28%22Never%20pass%20alerts%20in%20GET%20params!%22%29%3B%3C%2Fscript%3E).

**Comment by propi** [comment]
flash messages added
