### ISSUE TITLE
CPV codes aren't shown in contract's display

### ISSUE THREAD

**Issue by jindrichmynarz** [opendatacz/pc-filing-app#15]
Contract view in `src/main/webapp/buyer-view-event.jsp` doesn't show CPV codes. Full URIs of CPV codes are searched in `src/main/webapp/js/cpv-codes.js`, where there are only CPV notations, so the CPV codes cannot be found.

Possible solution: make the contract's view fetch CPV code's label (+ notation?) for display purposes?

**Comment by propi** [comment]
Fixed
