### ISSUE TITLE
Emails should be localizable

### ISSUE THREAD

**Issue by jindrichmynarz** [opendatacz/pc-filing-app#16]
Emails that the application sends (for example, [here](https://github.com/opendatacz/pc-filing-app/blob/develop/src/main/java/cz/opendata/tenderstats/InvitationComponent.java#L256-259) in `InvitationComponent.java`) should be localizable.

Possible solution: extract them from source code into localizable templates.

**Comment by propi** [comment]
Now all emails, except of the invitation email, are disabled. The invitation email is localized!
