### ISSUE TITLE
Deleting private contracts doesn't work

### ISSUE THREAD

**Issue by jindrichmynarz** [opendatacz/pc-filing-app#18]
Deleting private contracts (in `buyer-prepared.jsp`) results in HTTP 400 error (see [example](http://localhost:8080/pc-filing-app/PCFilingApp?forward=buyer-prepared.jsp&action=deletePrivateContract&contractURI=http://linked.opendata.cz/resource/public-contract/d17f8f72-48a0-493f-8427-708d49728dc1)).

**Comment by propi** [comment]
Fixed
