### ISSUE TITLE
Improve copy on the home page

### ISSUE THREAD

**Issue by jindrichmynarz** [opendatacz/pc-filing-app#20]
The application home page should contain a better description of options for contracting authorities and bidders.

**Comment by jindrichmynarz** [comment]
@svatek, has this issue been sufficiently addressed?

**Comment by svatek** [comment]
"PC Filing App is an application for public procurement." is a bit too laconic. I suggest adding a few sentences on the types of support the current version provides.
The LOD2 logo should be added, as well as a sentence about the funding from this project:
"The development of the PC Filing App is funded from the LOD2 project, EU FP7 no. 257943."

**Comment by jindrichmynarz** [comment]
I've added the LOD2 logo and acknowledgements (@jakhrkal, could you add Czech translations?). I suggest that the application's description is kept laconic and more detailed description is provided separately, as in #14.

**Comment by svatek** [comment]
"I suggest that the application's description is kept laconic and more detailed description is provided separately, as in #14."
Agreed.
