### ISSUE TITLE
Pagination error

### ISSUE THREAD

**Issue by propi** [opendatacz/pc-filing-app#23]
In supplier-calls.jsp, if you click to the "First" button within pagination, the application throws javascript error.

**Comment by jindrichmynarz** [comment]
I cannot reproduce this error on http://lod2.vse.cz:8090. Please describe in more detail how to reproduce it.

**Comment by propi** [comment]
I don't understand it! Now it works! It was probably some random, strange and irreproducible error:)

**Comment by jindrichmynarz** [comment]
Closing as not reproducible.

**Comment by propi** [comment]
"javascript exception: invalid date" when I click to the first page button...
