### ISSUE TITLE
Private header should be localizable

### ISSUE THREAD

**Issue by jindrichmynarz** [opendatacz/pc-filing-app#27]
Private header (`WEB-INF/jspf/header-private.jspf`) shouldn't contain hard-coded strings, such as "Logged in as", which should be drawn from the i18n files. It also shouldn't hard-code logout messages URI-encoded into logout link.

**Comment by jakhrkal** [comment]
The "Please fill out this field" notification during registration should be localizable as well.

**Comment by jindrichmynarz** [comment]
Where does this string come from (what page)?

**Comment by jakhrkal** [comment]
Registration page of both contracting authority and bidder - 
http://lod2.vse.cz:8080/pc-filing-app/register-buyer.jsp  and 
http://lod2.vse.cz:8080/pc-filing-app/register-supplier.jsp

**Comment by jindrichmynarz** [comment]
These are HTML5 native messages, so they aren't provided by the application, but by the browser. However, they can be customised to some degree, which is what I have done in d0c6d30b4188f4f94f71b2b3c1f13b22ce3fb6b2.

**Comment by jindrichmynarz** [comment]
@jakhrkal please confirm if this is fixed and if so, then close the issue.

**Comment by jakhrkal** [comment]
Fixed
