### ISSUE TITLE
Encoding of Czech characters in login messages

### ISSUE THREAD

**Issue by svatek** [opendatacz/pc-filing-app#30]
Login message does not display Czech characters properly.
![pcfa-issue-encoding](https://cloud.githubusercontent.com/assets/6616138/3875080/1233a4d6-214c-11e4-94a4-9c12e3e13069.png)

**Comment by jindrichmynarz** [comment]
I cannot reproduce this issue on OS X neither in Google Chrome nor in Firefox. May it be an IE/Windows-only issue?

**Comment by jindrichmynarz** [comment]
This issue is related to [ISSUE #1](https://github.com/opendatacz/pc-filing-app/issues/1). Alert messages to the users must not be passed via URI query parameters, especially when their content is interpreted as HTML + JavaScript.

**Comment by propi** [comment]
Encoding fixes
