### ISSUE TITLE
Showing the current call and matched contract side by side in detail

### ISSUE THREAD

**Issue by svatek** [opendatacz/pc-filing-app#34]
Never mind computing partial scores of individual matchers. 
But, just showing the current and matched contract in 2 columns in a single page (when clicking on a "Compare" option next to the matched contract) would help a lot. The user could then make the comparison somewhat manually. 
This should be mainly a simple GUI excercise, right? ...as soon as issue #32 is resolved...

**Comment by jindrichmynarz** [comment]
Yes, this can be done fairly easily. However, we first need a corresponding server-side code to retrieve both the matched contract and the matching contract and make them available in a new JSP template. This is why I've changed the assignment of this issue.
