### ISSUE TITLE
Non-functional Filter, Customize, Layout and Magnifier buttons

### ISSUE THREAD

**Issue by jakhrkal** [opendatacz/pc-filing-app#37]
The Filter items, Customize columns and Switch layout buttons eg. at http://lod2.vse.cz:8080/pc-filing-app/supplier-calls.jsp do not seem to be working.
![screenshot-2](https://cloud.githubusercontent.com/assets/7760136/3951665/b345588c-26d9-11e4-9935-9f3a99710587.png)

Same for the magnifier sign at registration screens (http://lod2.vse.cz:8080/pc-filing-app/register-buyer.jsp and http://lod2.vse.cz:8080/pc-filing-app/register-supplier.jsp)
![screenshot-6](https://cloud.githubusercontent.com/assets/7760136/3951695/02f7e016-26da-11e4-9df9-a12b459a48a7.png)

If possible, make these buttons do something, otherwise remove them.

**Comment by jindrichmynarz** [comment]
Addressed by c0a96ad7cb7c2666ccc6919277f7303fdb029cf9 and cfba6d395e6c10b3599aa279fa57dadaf349700e by removing the non-functional buttons.
