### ISSUE TITLE
Minor fixes and suggestions for the bidder side interface

### ISSUE THREAD

**Issue by svatek** [opendatacz/pc-filing-app#38]
1) Typo in the Czech menu: "Moje nabíkdy"
2) In the details of a proposed call, when there is no values for "Estimated start - end date", an interactive calender is displayed instead. I would expect something like "N/A".
3) For reading the text on the call, it would be helpful to distinguish parameters (e.g., Procurement method) and values (e.g., Open) fontwise or so.

**Comment by jindrichmynarz** [comment]
Fixed on the develop branch in 4dfbfab5144ff2fa36e5c5737b10100e7d13110e, c6e141c74d23e5017cb804c6820c6c958e584148, and 03fa6283f0d14532723ec963daa05b92d1902027.
