### ISSUE TITLE
Helping explanation for CPV codes during registration + more user-friendly way to input them

### ISSUE THREAD

**Issue by jindrichmynarz** [opendatacz/pc-filing-app#41]
There should be a helpful explanation of CPV codes in the bidder registration form. Also, a more user-friendly way to input them is needed. The issue has been raised by Martin Kaltenböck in his review comments.

**Comment by jindrichmynarz** [comment]
@svatek, @jakhrkal: Can you think of a more user-friendly way how to improve entry of CPV codes?

**Comment by svatek** [comment]
Whether on the bidder or CA side, a caveat is the fixed number of autocompletions displayed. Would it be possible to allow to scroll down if the current list is longer? Sometimes the user would not want to further extend the string, as s/he might lose some relevant autocompletions (e.g., verb vs. noun).

**Comment by jakhrkal** [comment]
Some basic explanation of what CPV codes are should be provided, either in the Help box, or the CPV fields could get their own help button. Also, as the application has Czech localization, it should be working with Czech CPV labels as well.

**Comment by jindrichmynarz** [comment]
@svatek, we can increase the number of suggestions shown by the autocomplete, but making it scrollable is more difficult (see e.g., [this fork of the autocompleter](https://github.com/tgirardi/twitter-bootstrap-typeahead/tree/scrollbar-support)) a potentially may result in worse usability due to fiddly UI.

**Comment by jindrichmynarz** [comment]
@jakhrkal, I've added a help popover to CPV fields in 183d462ff8855116fb437074a330c9ae33fc749e, so you can add a text explaining the codes using the i18n files. You may link to http://simap.europa.eu/codes-and-nomenclatures/codes-cpv/codes-cpv_en.htm.

**Comment by jakhrkal** [comment]
Added description of CPV in https://github.com/opendatacz/pc-filing-app/commit/36aebae7ccd76eb4b46b872fbc24a364bbc9abf9#diff-d41d8cd98f00b204e9800998ecf8427e . However, I was not able to create link to http://simap.europa.eu/codes-and-nomenclatures/codes-cpv/codes-cpv_en.htm , which would be useful. Could someone else do that?

**Comment by jindrichmynarz** [comment]
Was it not possible via `<a href="http://simap.europa.eu/codes-and-nomenclatures/codes-cpv/codes-cpv_en.htm">CPV codes</a>` in the i18n file?

**Comment by jakhrkal** [comment]
It was not. The result of that looks like this:
![screenshot](https://cloud.githubusercontent.com/assets/7760136/4000674/f9dcd32c-295b-11e4-96ab-4b8da3aec219.png)
The help button gets completely messed up. I suppose either some special chars in the reference should be escaped or the method in register-supplier.jsp used to invoke the text should be modified to read the tags correctly(?)

**Comment by jindrichmynarz** [comment]
I managed to get this working in 1a9c6be7ca8c2a52466e33c0de1240880cbb2564. The solution is to:
1. escape `=` as `\=` (this is a requirement of the Java properties format)
2. use single quotes because the text is used as an attribute value, which is enclosed in double quotes
