### ISSUE TITLE
Update terminology in templates

### ISSUE THREAD

**Issue by jindrichmynarz** [opendatacz/pc-filing-app#5]
The terminology used in templates (IDs of localized texts) should be updated to better match established terminology and be more aligned with the [Public Contracts Ontology](https://code.google.com/p/public-contracts-ontology/source/browse/public-contracts.ttl). For example:
- event => contract
- buyer => contracting authority
- supplier => bidder

**Comment by jakhrkal** [comment]
Issue should be solved, @jindrichmynarz , could you check it and if so, close the issue?
