### ISSUE TITLE
Saving a created contract fails

### ISSUE THREAD

**Issue by svatek** [opendatacz/pc-filing-app#55]
Saving a newly created contract (from http://lod2.vse.cz:8080/pc-filing-app/buyer-create-event.jsp) produced the following error, both in FF and Chrome. Currently cannot be replicated since contract cannot be filled due to non-functional autocompletion of CPV and NUTS.

HTTP Status 500 -

type Exception report
message
description The server encountered an internal error () that prevented it from fulfilling this request.
exception
com.hp.hpl.jena.query.QueryParseException: Encountered " "<" "< "" at line 35, column 1673.
Was expecting one of:
    <IRIref> ...
    <PNAME_NS> ...
    <PNAME_LN> ...
    <BLANK_NODE_LABEL> ...
    <VAR1> ...
    <VAR2> ...
    "true" ...
    "false" ...
    <INTEGER> ...
    <DECIMAL> ...
    <DOUBLE> ...
    <INTEGER_POSITIVE> ...
    <DECIMAL_POSITIVE> ...
    <DOUBLE_POSITIVE> ...
    <INTEGER_NEGATIVE> ...
    <DECIMAL_NEGATIVE> ...
    <DOUBLE_NEGATIVE> ...
    <STRING_LITERAL1> ...
    <STRING_LITERAL2> ...
    <STRING_LITERAL_LONG1> ...
    <STRING_LITERAL_LONG2> ...
    "(" ...
    <NIL> ...
    "[" ...
    <ANON> ...

```
com.hp.hpl.jena.sparql.lang.ParserARQUpdate._parse(ParserARQUpdate.java:67)
com.hp.hpl.jena.sparql.lang.ParserARQUpdate.parse$(ParserARQUpdate.java:40)
com.hp.hpl.jena.sparql.lang.UpdateParser.parse(UpdateParser.java:42)
com.hp.hpl.jena.update.UpdateFactory.make(UpdateFactory.java:90)
com.hp.hpl.jena.update.UpdateFactory.create(UpdateFactory.java:81)
com.hp.hpl.jena.update.UpdateFactory.create(UpdateFactory.java:59)
com.hp.hpl.jena.update.UpdateFactory.create(UpdateFactory.java:49)
cz.opendata.tenderstats.pcfapp.PCFappModelContract.addPrivateContract(PCFappModelContract.java:706)
cz.opendata.tenderstats.PCFilingApp.doGetPost(PCFilingApp.java:479)
cz.opendata.tenderstats.AbstractComponent.doPost(AbstractComponent.java:167)
javax.servlet.http.HttpServlet.service(HttpServlet.java:641)
javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
cz.opendata.tenderstats.FlashMessage.doFilter(FlashMessage.java:40)
org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108)
```

note The full stack trace of the root cause is available in the Apache Tomcat/7.0.26 logs.

Apache Tomcat/7.0.26

**Comment by jindrichmynarz** [comment]
For future notice, this was closed by fb77cfcbc75046c393eeec3ce0f74f0cca7acabe, by correcting the format of CPV URIs.
